language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn build
env:
  - REACT_APP_API_ENDPOINT=https://still-headland-30261.herokuapp.com/graphql
  - NODE_ENV=production
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
