import { CssBaseline } from '@mui/material';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import { green, grey } from '@mui/material/colors';
import Head from 'next/head';
import { ApolloProvider } from '@apollo/client';
import type { AppProps } from 'next/app';
import { UserProvider } from '@auth0/nextjs-auth0';
import { initApolloClient } from '../client';

const theme = createTheme({
  palette: {
    mode: 'dark',
  },
});

export default function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <UserProvider>
        <ApolloProvider client={initApolloClient()}>
          <Head>
            <title>Create Next App</title>
            <meta content="Generated by create next app" name="description" />
            <link href="/favicon.ico" rel="icon" />
            <link
              crossOrigin=""
              href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
              integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
              rel="stylesheet"
            />
            <link
              crossOrigin=""
              href="https://api.mapbox.com/mapbox-gl-js/v2.6.0/mapbox-gl.css"
              rel="stylesheet"
            />
          </Head>
          <Component {...pageProps} />
        </ApolloProvider>
      </UserProvider>
    </ThemeProvider>
  );
}
