import Head from 'next/head'
import styled from 'styled-components';

const StyledDiv = styled.div`
  padding: 16px;
  background-color: #fafafa;
`

export default function Home(props) {
  console.log({ props })

  return (
    <StyledDiv>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>hello, world</h1>
      </main>
    </StyledDiv>
  )
}
